### ISSUE TITLE
What is the purpose of the `release/4.3.0` branch?

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/cva6#1046]
I just discovered a branch of this repo called `release/4.3.0`.  It was last updated by @atkarim 10 months ago.  As far as I am aware, there is no pending 4.3.0 release of the CVA6 and [atkarim](https://github.com/atkarim) is not an OpenHW Contributor, nor are they active on GitHub.

I believe `release/4.3.0` is probably a dead branch and can be safely deleted.  Please let me know if there are any objections to this: @zarubaf, @Jbalkind, @JeanRochCoulon, @jquevremont.

**Comment by atkarim** [comment]
Hi Mike,
I pushed my commit to this branch, because I thought it was the development branch.
If this branch is deleted, I think it's important to push my commit to the correct branch, as there is an unused argument in a bootrom function.

**Comment by JeanRochCoulon** [comment]
Hello @atkarim,  The best way would be to submit a PR on the cva6/cva6/dev branch. If I understood, the 4.3.0 name will not be reused, v5.0.0 should be the magic version name !

**Comment by MikeOpenHWGroup** [comment]
Hi @atkarim.  After some internal discussion, the following changes have been made to this repo:
1. The `dev` branch has been frozen.  It still exists, but you cannot issue pull-requests to it.
2. The `cv32a6_v0.1.0` branch has been renamed `cv32a6_v5.0.0` [link](https://github.com/openhwgroup/cva6/tree/cv32a6_v5.0.0).

So I would like to remove the `release/4.3.0` branch.  I will not do so until you've had time to move your files/forks as needed.   Please let me know when this is done.

Thanks!

**Comment by atkarim** [comment]
Hi Mike,

It's ok.
You can remove the `release/4.3.0` branch without any problem for me.

Thanks for waiting!

**Comment by MikeOpenHWGroup** [comment]
Done!   Thanks @atkarim.  `release/4.3.0` has been deleted.

We have adopted a new protocol for handling Issues in which the **Originator** (you, in this case) is the person who closes the Issue.  Please check that everything is good on your end and if so, close this issue.

**Comment by atkarim** [comment]
Hi @MikeOpenHWGroup,

I am assigned but I cannot close the issue, I can only comment.
I think I am not really the originator, as I didn't open this issue.

Can you close it for me please, thanks.
